"""
asset_generation.py
====================
Generates the "Phase 2" educational assets -- FAQs, example/practice
programs, chapter/module/pillar overviews, flashcards, and module
quizzes -- that sit alongside a page's main content generated by
ai_content.py.

Entirely optional and additive: nothing in Pipeline.run_ai() or
generate_content_ai() calls anything in this file. It's driven by the
new /pipeline/assets/... routes only.

Each generate_* function returns a dict (or, for flashcards, a list)
already shaped exactly like the payload the real backend endpoint
expects -- see api_client.py for exactly which endpoint/method each one
is POSTed/PUT to. No translation layer between "what Claude generates"
and "what gets submitted", same principle ai_content.py already follows
for regular page content.
"""
from __future__ import annotations

import json
import re

from anthropic import Anthropic

from . import demo_content
from .prompts import get_prompt

ASSET_TYPES = {
    "faq": "FAQ",
    "example_program": "Example Program",
    "practice_program": "Practice Program",
    "chapter_overview": "Chapter Overview",
    "module_overview": "Module Overview",
    "pillar_overview": "Pillar Overview",
    "flashcards": "Flashcards",
    "module_quiz": "Module Quiz",
}

# Which hierarchy level(s) each asset type can be generated for, and which
# kind of id its submission endpoint needs. Both are used by the routes
# layer to build the hub page and to resolve the right id before submitting.
APPLICABLE_LEVELS = {
    "faq": ["page", "chapter", "module", "pillar"],
    "example_program": ["page", "chapter"],
    "practice_program": ["page", "chapter", "module"],
    "chapter_overview": ["chapter"],
    "module_overview": ["module"],
    "pillar_overview": ["pillar"],
    "flashcards": ["page", "chapter", "module"],
    "module_quiz": ["module"],
}


def _client(cfg) -> Anthropic:
    if not cfg.anthropic_api_key:
        raise RuntimeError("ANTHROPIC_API_KEY is required for asset generation.")
    return Anthropic(api_key=cfg.anthropic_api_key)


def _model(cfg) -> str:
    return getattr(cfg, "content_model", None) or "claude-sonnet-4-6"


def _ask_json(cfg, system: str, user: str, max_tokens: int = 3000) -> dict:
    resp = _client(cfg).messages.create(
        model=_model(cfg), max_tokens=max_tokens, system=system,
        messages=[{"role": "user", "content": user}],
    )
    text = "".join(b.text for b in resp.content if b.type == "text")
    text = re.sub(r"^```json|```$", "", text.strip(), flags=re.MULTILINE).strip()
    return json.loads(text)


# ---------------------------------------------------------------------
# 1. FAQ  ->  POST /api/pages/<id>/content  (same shape as a regular page:
#    {"title": "FAQs", "sections": [...]})
# ---------------------------------------------------------------------
def generate_faq(title: str, breadcrumb: str, cfg) -> dict:
    # Prompt text lives in prompts/faq_prompt.txt (see elluval_pipeline/prompts.py).
    system = get_prompt("faq_prompt")
    if getattr(cfg, "is_demo_mode", False):
        generated = demo_content.generate_demo_faq(title, breadcrumb)
    else:
        generated = _ask_json(cfg, system, breadcrumb)
    return {
        "title": "FAQs",
        "sections": [{"type": "html", "value": generated.get("faq_html", "")}],
    }


# ---------------------------------------------------------------------
# 2 & 3. Example / Practice programs -> POST /api/compiler/practice/chapter/<id>
#    {"title","description","language","starterCode","starterSourceFiles",
#     "solutionCode","solutionSourceFiles","programType","testCases"}
# ---------------------------------------------------------------------
def _generate_program(title: str, breadcrumb: str, cfg, program_type: str) -> dict:
    difficulty_hint = (
        "basic, intermediate, advanced, real-world, production-grade, and "
        "industry-style" if program_type == "EXAMPLE" else
        "beginner, intermediate, advanced, and a challenge problem"
    )
    role_label = "a worked example" if program_type == "EXAMPLE" else "a practice exercise"
    # Prompt text lives in prompts/program_prompt.txt (see elluval_pipeline/prompts.py).
    system = get_prompt("program_prompt", role_label=role_label, difficulty_hint=difficulty_hint)
    if getattr(cfg, "is_demo_mode", False):
        generated = demo_content.generate_demo_program(title, breadcrumb, program_type)
    else:
        generated = _ask_json(cfg, system, breadcrumb)
    return {
        "title": generated.get("title", title),
        "description": generated.get("description", ""),
        "language": generated.get("language", "text"),
        "starterCode": generated.get("starterCode", ""),
        "starterSourceFiles": {},
        "solutionCode": generated.get("solutionCode", ""),
        "solutionSourceFiles": {},
        "programType": program_type,
        # The real shape of an individual test case wasn't specified beyond
        # an empty list in the reference payload, so this is left for the
        # reviewer to fill in manually during review rather than guessed at.
        "testCases": [],
    }


def generate_example_program(title: str, breadcrumb: str, cfg) -> dict:
    return _generate_program(title, breadcrumb, cfg, "EXAMPLE")


def generate_practice_program(title: str, breadcrumb: str, cfg) -> dict:
    return _generate_program(title, breadcrumb, cfg, "PRACTICE")


# ---------------------------------------------------------------------
# 4/5/6. Chapter / Module / Pillar overview -> PUT .../overview
#    {"overviewSummary","overviewHtml","overviewPublished","overviewHighlights"}
# ---------------------------------------------------------------------
def _generate_overview(level_name: str, title: str, breadcrumb: str, cfg, extra_fields: str) -> dict:
    # Prompt text lives in prompts/overview_prompt.txt (see elluval_pipeline/prompts.py).
    system = get_prompt("overview_prompt", level_name=level_name, extra_fields=extra_fields)
    if getattr(cfg, "is_demo_mode", False):
        generated = demo_content.generate_demo_overview(level_name, title, breadcrumb)
    else:
        generated = _ask_json(cfg, system, breadcrumb)
    return {
        "overviewSummary": generated.get("summary", ""),
        "overviewHtml": generated.get("html", ""),
        "overviewPublished": False,
        "overviewHighlights": generated.get("highlights", []),
    }


def generate_chapter_overview(title: str, breadcrumb: str, cfg) -> dict:
    return _generate_overview(
        "chapter", title, breadcrumb, cfg,
        "learning objectives, prerequisites, topics covered, expected "
        "outcomes, estimated learning time, and real-world relevance",
    )


def generate_module_overview(title: str, breadcrumb: str, cfg) -> dict:
    return _generate_overview(
        "module", title, breadcrumb, cfg,
        "module objectives, skills acquired, chapters included and their "
        "recommended order, industry relevance, and career applicability",
    )


def generate_pillar_overview(title: str, breadcrumb: str, cfg) -> dict:
    return _generate_overview(
        "pillar", title, breadcrumb, cfg,
        "the purpose of the pillar, the learning journey through it, "
        "major concepts covered, dependencies on previous pillars, and "
        "expected mastery level by the end",
    )


# ---------------------------------------------------------------------
# 7. Flashcards -> PUT /api/curriculum/modules/<id>/flashcards
#    [{"frontText": "...", "backText": "..."}, ...]   (payload is a LIST)
# ---------------------------------------------------------------------
def generate_flashcards(title: str, breadcrumb: str, cfg, count: int = 12) -> list:
    # Prompt text lives in prompts/flashcard_prompt.txt (see elluval_pipeline/prompts.py).
    system = get_prompt("flashcard_prompt", count=count)
    if getattr(cfg, "is_demo_mode", False):
        generated = demo_content.generate_demo_flashcards(title, breadcrumb, count)
    else:
        generated = _ask_json(cfg, system, breadcrumb, max_tokens=2500)
    return [
        {"frontText": c.get("front", ""), "backText": c.get("back", "")}
        for c in generated.get("cards", [])
    ]


# ---------------------------------------------------------------------
# 8. Module Quiz -> PUT /api/curriculum/modules/<id>/quiz?subjectId=<id>
#    {"title","passPercent","published","questions":[...]}
# ---------------------------------------------------------------------
def generate_module_quiz(title: str, breadcrumb: str, cfg, num_questions: int = 10) -> dict:
    # Prompt text lives in prompts/quiz_prompt.txt (see elluval_pipeline/prompts.py).
    system = get_prompt("quiz_prompt", num_questions=num_questions)
    if getattr(cfg, "is_demo_mode", False):
        generated = demo_content.generate_demo_quiz(title, breadcrumb, num_questions)
    else:
        generated = _ask_json(cfg, system, breadcrumb, max_tokens=4000)
    questions = []
    for q in generated.get("questions", []):
        questions.append({
            "prompt": q.get("prompt", ""),
            "questionType": q.get("questionType", "SINGLE_CHOICE"),
            "codeSnippet": q.get("codeSnippet", ""),
            "codeLanguage": q.get("codeLanguage", "java"),
            "options": [
                {"label": o.get("label", ""), "correct": bool(o.get("correct", False))}
                for o in q.get("options", [])
            ],
        })
    return {
        "title": f"{title} Quiz",
        "passPercent": 70,
        "published": False,
        "questions": questions,
    }


GENERATORS = {
    "faq": generate_faq,
    "example_program": generate_example_program,
    "practice_program": generate_practice_program,
    "chapter_overview": generate_chapter_overview,
    "module_overview": generate_module_overview,
    "pillar_overview": generate_pillar_overview,
    "flashcards": generate_flashcards,
    "module_quiz": generate_module_quiz,
}
